# Generated by Django 3.2.8 on 2021-11-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WwgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('user_pwd', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='zerowaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('imgURL', models.CharField(max_length=1000)),
                ('img', models.CharField(max_length=300)),
                ('lat', models.IntegerField()),
                ('lng', models.IntegerField()),
            ],
        ),
    ]
