# Generated by Django 3.2.8 on 2021-11-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0002_wwg_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='vegan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('imgURL', models.CharField(max_length=1000)),
                ('img', models.CharField(max_length=300)),
                ('lat', models.IntegerField()),
                ('lng', models.IntegerField()),
            ],
        ),
    ]
