# Generated by Django 3.2.8 on 2021-11-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0004_auto_20211112_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='WwgVeganClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('cnt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WwgZerowasteClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('cnt', models.IntegerField()),
            ],
        ),
    ]
