# Generated by Django 3.2.8 on 2021-11-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0006_auto_20211116_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopVegan', models.CharField(max_length=5000)),
                ('TopZerowaste', models.CharField(max_length=5000)),
                ('Date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VeganClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('name_index', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('WWGScore', models.FloatField()),
                ('cnt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WwgUserRecomm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('vegan_recomm', models.CharField(max_length=5000)),
                ('zerowaste_recomm', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='ZerowasteClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('name_index', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('WWGScore', models.FloatField()),
                ('cnt', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='WwgClick',
        ),
        migrations.DeleteModel(
            name='WwgVeganClick',
        ),
        migrations.DeleteModel(
            name='WwgZerowasteClick',
        ),
        migrations.AddField(
            model_name='wwgvegan',
            name='Recomm',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='wwgvegan',
            name='WWGScore',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='wwgvegan',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='wwgvegan',
            name='review1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='wwgvegan',
            name='review2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='wwgzerowaste',
            name='Recomm',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='wwgzerowaste',
            name='WWGScore',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='wwgzerowaste',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='wwgzerowaste',
            name='review1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='wwgzerowaste',
            name='review2',
            field=models.FloatField(null=True),
        ),
    ]
