# Generated by Django 3.2.8 on 2021-11-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapApp', '0007_auto_20211119_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wwgvegan',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wwgvegan',
            name='lng',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wwgvegan',
            name='number',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='wwgzerowaste',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wwgzerowaste',
            name='lng',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='wwgzerowaste',
            name='number',
            field=models.CharField(max_length=200),
        ),
    ]
