# Generated by Django 3.2.5 on 2021-11-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardApp', '0002_board_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='image',
        ),
        migrations.AddField(
            model_name='board',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
