# Generated by Django 3.2.5 on 2021-11-15 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardApp', '0003_auto_20211116_0426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='imgfile',
            new_name='mainphoto',
        ),
    ]
