# Generated by Django 3.2.9 on 2021-11-16 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardApp', '0004_rename_imgfile_board_mainphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='mainphoto',
            field=models.ImageField(blank=True, null=True, upload_to='mainphoto'),
        ),
    ]
