# Generated by Django 3.2.5 on 2021-11-22 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardApp', '0006_board2_mainphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='board2',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
